image: Visual Studio 2017
platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable -y
  - if not exist gtk-sharp-2.12.26.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
  - msiexec /i gtk-sharp-2.12.26.msi /qn /norestart
  - if not exist gtk-sharp-2.99.3.msi appveyor DownloadFile https://download.gnome.org/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
  - msiexec /i gtk-sharp-2.99.3.msi /qn /norestart

cache:
  - gtk-sharp-2.12.26.msi
  - gtk-sharp-2.99.3.msi

before_build:
  - NuGet restore Source/OxyPlot.GtkSharp.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Source/OxyPlot.GtkSharp.sln
  verbosity: minimal
 
after_build:
  - NuGet pack Source\OxyPlot.GtkSharp\OxyPlot.GtkSharp.nuspec -version "%GitVersion_NuGetVersion%"
  - NuGet pack Source\OxyPlot.GtkSharp\OxyPlot.GtkSharp3.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/oxyplot/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
